# Generated by Django 5.0.2 on 2024-06-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(blank=True, choices=[('AMD', 'AMD'), ('NVIDIA', 'NVIDIA')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('U', 'Unpaid'), ('P', 'Paid')], default='U', max_length=1),
        ),
    ]
