# Generated by Django 5.0.2 on 2024-06-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_category_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('AMD', 'AMD'), ('NVIDIA', 'NVIDIA')], max_length=6, null=True),
        ),
    ]
